services:
  postgres:
    image: 'postgres:18.4-alpine'
    restart: always
    environment:
      POSTGRES_DB: 'kimflights'
      POSTGRES_USER: 'sa'
      POSTGRES_PASSWORD: 'mysecretpassword'
    ports:
      - '5432:5432'
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: kimflights-app
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - postgres
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/kimflights
  #     SPRING_DATASOURCE_USERNAME: sa
  #     SPRING_DATASOURCE_PASSWORD: mysecretpassword
